[package]
name = "ruspec"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "0.15.28", features = ["full"] }
proc-macro2 = "0.4.27"
quote = "0.6"
failure = "0.1.5"
colored = "1.7.0"
Inflector = "0.11.4"

[lib]
proc_macro = true
